library('magick')
# Example image
frink <- image_read("https://jeroen.github.io/images/frink.png")
print(frink)
#hist(frink)
ros_image <- image_read("/home/ros/Bilder/17_Extern/Export/R/2017_02_03_19_49_45_L.jpg")
str(ros_image)
ros_small <- image_scale(ros_image,"x400")
print(ros_small)
print(ros_image)
